### ISSUE TITLE
Missing misc_tools.math Module

### ISSUE THREAD

**Issue by michaeljp24** [mpierzyna/wrf_cn2_intercomp#1]
Hello,

It seems that in post_proc, the utils.py module requires a misc_tools.math package with a gradient_nonuniform function that is not included in the distribution. 

Can you add the missing file?

**Comment by maxiimilian** [comment]
Hi Michael,

I am sorry for the slow reply and the oversight. I have added that file in the latest commit. Thanks for your interest in using my code. Let me know if you encounter any more issues. 

Max
